#CCE_Board_Definitions:BHI160;BHI160B;BHA250

COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= bhy_gesture_recognition.c

SHUTTLE_BOARD ?= BHI160

CFLAGS += -DBST_APPBOARD_VIA_USB -D$(SHUTTLE_BOARD) 

include $(COINES_INSTALL_PATH)/examples/examples.mk
